name: Scheduled Script with Email Notification

on:
  schedule:
    - cron: '0 8 * * *' # Runs every day at 8 AM UTC

jobs:
  run-and-notify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sendgrid python-dotenv
    - name: Run script and send email
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: |
        python price-drop.py  # Replace with the path to your script
        python send_email.py   # This script will send the email using SendGrid
