name: Scheduled Script Execution with Email Notification

on:
  schedule:
    - cron: '0 8 * * *' # Runs every day at 8 AM UTC. Adjust according to your needs.
  push: # Temporary trigger for testing. Remove or comment out when not needed.
    branches:
      - master # Adjust this to match your default branch if it's not 'main'.

jobs:
  execute-and-notify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version you need.

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download geckodriver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
        tar -xzf geckodriver-v0.34.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/

    - name: Run script
      run: python price-drop.py # Replace with the path to your script.

    - name: Send email notification
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      run: python send_email.py # Assumes you have this script for sending emails via SendGrid.
